/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkg3a.ui;

import java.awt.Frame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import pkg3a.utils.Customer;
import pkg3a.utils.DBUtil;
import pkg3a.utils.DBUtil.InsertDbListener;

/**
 *
 * @author yazeed44
 */
public class AddCustomerDialog extends javax.swing.JDialog {

    private AddCustomerCallback mCallback;
    /** Creates new form AddCustomerDialog */
    public AddCustomerDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public AddCustomerDialog(final Frame parent , AddCustomerCallback callback){
    this(parent,true);
    mCallback = callback;
    }
    
    public static void showAddCustomerDialog(final Frame parent,AddCustomerCallback callback){
        new AddCustomerDialog(parent,callback).setVisible(true);
         
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mobileNumberText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phoneNumberText = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        companyNameText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addressText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("KacstOne", 1, 12)); // NOI18N
        jLabel1.setText("إسم العميل");

        nameText.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("KacstOne", 1, 12)); // NOI18N
        jLabel2.setText("رقم الجوال");

        jLabel3.setFont(new java.awt.Font("KacstOne", 1, 12)); // NOI18N
        jLabel3.setText("رقم الهاتف");

        submitButton.setFont(new java.awt.Font("KacstOne", 1, 14)); // NOI18N
        submitButton.setText("إضافة");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("KacstOne", 1, 14)); // NOI18N
        cancelButton.setText("إلغاء");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("KacstOne", 1, 12)); // NOI18N
        jLabel4.setText("إسم الشركة");

        jLabel5.setFont(new java.awt.Font("KacstOne", 1, 12)); // NOI18N
        jLabel5.setText("العنوان");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nameText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submitButton)
                        .addGap(13, 13, 13)
                        .addComponent(cancelButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressText, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(phoneNumberText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(companyNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(mobileNumberText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mobileNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(phoneNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(companyNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        submit();
    }//GEN-LAST:event_submitButtonActionPerformed

    protected void submit() {
        final Customer customer = createBuilder(-1).build();
        
        if (customer == null){
        return;
        }
        
        DBUtil.insertCustomer(customer, new InsertDbListener(){

            @Override
            public void insertedSuccessfully() {
                mCallback.addedSuccessfully(AddCustomerDialog.this);
            }

            @Override
            public void failedToInsert(Throwable throwable) {
                
                SwingUtilities.invokeLater(new Runnable(){

                    @Override
                    public void run() {
                          JOptionPane.showMessageDialog(AddCustomerDialog.this, "إسم العميل مكرر !!", "خطأ", JOptionPane.ERROR_MESSAGE);
                    }
                });
                
              
                
                mCallback.failedToAdd(AddCustomerDialog.this, throwable);
            }
        });
    }
    
    protected Customer.Builder createBuilder(final int id){
        
        final String name = nameText.getText();
        
        if (!isValidString(name)){
        JOptionPane.showMessageDialog(this, "خطأ في اسم العميل", "خطأ", JOptionPane.ERROR_MESSAGE);
        return null;
        }
        
    final Customer.Builder builder = new Customer.Builder(name, id);
    
    final String companyName  = companyNameText.getText();
    if (isValidString(companyName)){
       builder.setCompany(companyName);
    
    }
    
    else {
         JOptionPane.showMessageDialog(this, "خطأ في اسم الشركة","خطأ",JOptionPane.ERROR_MESSAGE);
        return null;
        
    }
    
    final String mobileNumber = mobileNumberText.getText();
    
    if (isValidString(mobileNumber)){
      builder.setMobileNumber(mobileNumber);
    }
    
    final String phoneNumber = phoneNumberText.getText();
    
    if (isValidString(phoneNumber)){
    builder.setPhoneNumber(phoneNumber);
    }
    
    
    
    
    
    final String address = addressText.getText();
    
    if (isValidString(address)){
     builder.setAddress(address);
    }
    
    
    return builder;
    
    
    }
    
    private boolean isValidString(String s){
    return s != null && s.length() > 0;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextField addressText;
    private javax.swing.JButton cancelButton;
    protected javax.swing.JTextField companyNameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    protected javax.swing.JTextField mobileNumberText;
    protected javax.swing.JTextField nameText;
    protected javax.swing.JTextField phoneNumberText;
    protected javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables

    

    public static interface AddCustomerCallback {
    void addedSuccessfully(AddCustomerDialog dialog);
    void failedToAdd(AddCustomerDialog dialog , Throwable error);
    }
}
