/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg3a.ui;

import java.awt.Frame;
import javax.swing.JOptionPane;
import pkg3a.utils.DBUtil;
import pkg3a.utils.HostingPackage;

/**
 *
 * @author yazeed44
 */
public class AddHostingPackageDialog extends javax.swing.JDialog implements DBUtil.InsertDbListener {

    private AddHostingPackageCallback mCallback;
    /**
     * Creates new form AddHostingPackageDialog
     */
    public AddHostingPackageDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    
    public AddHostingPackageDialog(Frame parent , final AddHostingPackageCallback callback){
        this(parent,true);
        mCallback = callback;
    }
    
    public static void showAddHostingPackageDialog(final Frame parent , final AddHostingPackageCallback callback){
        new AddHostingPackageDialog(parent,callback).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        yearPriceText = new javax.swing.JFormattedTextField();
        storageSpaceText = new javax.swing.JFormattedTextField();
        monthlyOfferText = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        emailsCountText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("KacstOne", 1, 12)); // NOI18N
        jLabel1.setText("إسم الباقة");

        nameText.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        nameText.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("KacstOne", 1, 12)); // NOI18N
        jLabel2.setText("المساحة التخزينية");

        jLabel3.setText("MB");

        jLabel4.setFont(new java.awt.Font("KacstOne", 1, 12)); // NOI18N
        jLabel4.setText("عرض الحزمة الشهري");

        jLabel5.setFont(new java.awt.Font("KacstOne", 1, 12)); // NOI18N
        jLabel5.setText("السعر");

        yearPriceText.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        yearPriceText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        storageSpaceText.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        storageSpaceText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        monthlyOfferText.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        monthlyOfferText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel6.setText("MB");

        jLabel7.setFont(new java.awt.Font("KacstOne", 1, 12)); // NOI18N
        jLabel7.setText("عدد الإيميلات");

        emailsCountText.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("KacstOne", 1, 12)); // NOI18N
        jLabel8.setText("سنويا");

        submitButton.setFont(new java.awt.Font("KacstOne", 1, 14)); // NOI18N
        submitButton.setText("إضافة");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("KacstOne", 1, 14)); // NOI18N
        cancelButton.setText("إلغاء");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(315, 315, 315)
                                        .addComponent(jLabel1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(storageSpaceText, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(monthlyOfferText, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(emailsCountText, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(yearPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 7, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(storageSpaceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthlyOfferText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(emailsCountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(yearPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        submit();
        
        
    }//GEN-LAST:event_submitButtonActionPerformed

    protected void submit(){
    final HostingPackage hostingPackage = createBuilder(-1).build();
    
    if (hostingPackage == null){
        return;
    }
   
    
    DBUtil.insertHostingPackage(hostingPackage, this);
    
    }
    
    protected HostingPackage.Builder createBuilder(final int id){
        
        final String name = nameText.getText();
        if (isTextEmpty(name)){
            JOptionPane.showMessageDialog(this, "إسم الباقة فارغ", "خطأ", JOptionPane.ERROR_MESSAGE,null);
            return null;
        }
    
        final HostingPackage.Builder builder = new HostingPackage.Builder(name, id);
        
        final int yearCost = parseInteger(yearPriceText.getText());
        
        if (yearCost == -1){
            JOptionPane.showMessageDialog(this, "خطأ في السعر !!", "خطأ", JOptionPane.ERROR_MESSAGE,null);
            return null;
            
        }
        
        builder.setYearCost(yearCost);
        
        final String monthlyOffer = monthlyOfferText.getText();
        
        if (!isTextEmpty(monthlyOffer)){
            builder.setMonthlyPackageOffer(monthlyOffer);
        }
        
        final String emailsCount = emailsCountText.getText();
        
        if (!isTextEmpty(emailsCount)){
            builder.setEmailsCount(emailsCount);
        }
        
        final String storageSpace = storageSpaceText.getText();
        
        if (!isTextEmpty(storageSpace)){
            builder.setStorageSpace(storageSpace);
        }
        
        return builder;
        
    }
    
    private int parseInteger(final String text){
    
         int i;
        try {
        
            i = Integer.parseInt(text);
        }
        
        catch(NumberFormatException ex){
        
            i = -1;
        }
        
        return i;
    }
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    
    private boolean isTextEmpty(final String s){
     return s == null || s.isEmpty();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton cancelButton;
    protected javax.swing.JTextField emailsCountText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    protected javax.swing.JFormattedTextField monthlyOfferText;
    protected javax.swing.JTextField nameText;
    protected javax.swing.JFormattedTextField storageSpaceText;
    protected javax.swing.JButton submitButton;
    protected javax.swing.JFormattedTextField yearPriceText;
    // End of variables declaration//GEN-END:variables

    @Override
    public void insertedSuccessfully() {
        mCallback.addedSuccessfully(this);
    }

    @Override
    public void failedToInsert(Throwable throwable) {
        mCallback.failedToAdd(this, throwable);
    }
    
    public static interface AddHostingPackageCallback {
        void addedSuccessfully(final AddHostingPackageDialog dialog);
        void failedToAdd(final AddHostingPackageDialog dialog , Throwable throwable);
    }
}
