/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg3a.ui;

import java.awt.Color;
import java.awt.Frame;
import java.awt.List;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.text.DateFormat;
import java.text.ParseException;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListDataListener;
import pkg3a.utils.Customer;
import pkg3a.utils.DBUtil;
import pkg3a.utils.DBUtil.InsertDbListener;
import pkg3a.utils.DBUtil.QueryDbListener;
import pkg3a.utils.HostingPackage;
import pkg3a.utils.Order;

/**
 *
 * @author yazeed44
 */
public class AddOrderDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddOrderDialog
     */
    private int mDomainPrice = 0;
    private AddDialogListener mAddListener;
    public AddOrderDialog(java.awt.Frame parent,boolean modal) {
        super(parent, true);
        initComponents();
        setupCustomerCombobox();
        setupPackageCombobox();
        setupDomainName();
        setTitle("إضافة طلبية");
        
       
        
    }
    
    public AddOrderDialog(Frame parent , final AddDialogListener listener){
        this(parent,true);
                mAddListener = listener;
    }
    
    public static void showAddDialog(final Frame parent , final AddDialogListener listener){
         new AddOrderDialog(parent,listener).setVisible(true);
    }
    
   
    
    private void setupCustomerCombobox(){
         DBUtil.loadCustomers(new QueryDbListener<ArrayList<Customer>>(){

                @Override
                public void queriedSuccessfully(ArrayList<Customer> result) {
                    customerCombobox.setModel(new CustomerComboboxModel(result));
                }

                @Override
                public void failedToQuery(Throwable throwable) {
                }
            });
    }
    
    private void setupPackageCombobox(){
         DBUtil.loadHostingPackages(new QueryDbListener<ArrayList<HostingPackage>>(){

                @Override
                public void queriedSuccessfully(ArrayList<HostingPackage> result) {
                    packageCombobox.setModel(new PackageComboboxModel(result));
                }

                @Override
                public void failedToQuery(Throwable throwable) {
                }
            });
    }
    
    
    
    private void setupDomainName(){
         domainCostTxt.addKeyListener(new KeyListener(){

            @Override
            public void keyTyped(KeyEvent e) {
                updateTotalCostOnChangingDomainCost();
            }

            @Override
            public void keyPressed(KeyEvent e) {
                updateTotalCostOnChangingDomainCost();
            }

            @Override
            public void keyReleased(KeyEvent e) {
                updateTotalCostOnChangingDomainCost();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        customerCombobox = new javax.swing.JComboBox();
        addButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        totalCostText = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        domainCostTxt = new javax.swing.JFormattedTextField();
        noteText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        domainNameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        domainCheckbox = new javax.swing.JCheckBox();
        packageCombobox = new javax.swing.JComboBox();
        domainEndDate = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("KacstOne", 1, 12)); // NOI18N
        jLabel7.setText("العميل");

        cancelButton.setFont(new java.awt.Font("KacstOne", 1, 12)); // NOI18N
        cancelButton.setText("إلغاء");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        customerCombobox.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        customerCombobox.setToolTipText("");

        addButton.setFont(new java.awt.Font("KacstOne", 1, 12)); // NOI18N
        addButton.setText("إضافة");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("KacstOne", 1, 12)); // NOI18N
        jLabel8.setText("قيمة الطلب");

        totalCostText.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        totalCostText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel4.setFont(new java.awt.Font("KacstOne", 1, 12)); // NOI18N
        jLabel4.setText("قيمة الدومين");
        jLabel4.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("KacstOne", 1, 12)); // NOI18N
        jLabel9.setText("ملاحظة");

        domainCostTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        domainCostTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        noteText.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("KacstOne", 1, 18)); // NOI18N
        jLabel5.setText("عام");

        jLabel6.setFont(new java.awt.Font("KacstOne", 1, 12)); // NOI18N
        jLabel6.setText("باقة الإستضافة");

        jLabel1.setFont(new java.awt.Font("KacstOne", 1, 18)); // NOI18N
        jLabel1.setText("الدومين");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("KacstOne", 1, 12)); // NOI18N
        jLabel2.setText("إسم الدومين");

        domainNameTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("KacstOne", 1, 12)); // NOI18N
        jLabel3.setText("تاريخ التجديد");

        domainCheckbox.setFont(new java.awt.Font("KacstOne", 1, 12)); // NOI18N
        domainCheckbox.setText("بدون دومين");
        domainCheckbox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                domainCheckboxStateChanged(evt);
            }
        });

        packageCombobox.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        packageCombobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                packageComboboxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(domainCheckbox)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(domainNameTxt)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(domainCostTxt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(domainEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jSeparator1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(customerCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel7)
                            .addGap(36, 36, 36)
                            .addComponent(packageCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel6))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(totalCostText)
                                .addComponent(noteText))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(domainCheckbox)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(domainNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(domainCostTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(domainEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(packageCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(customerCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelButton)
                            .addComponent(addButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(totalCostText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(noteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void domainCheckboxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_domainCheckboxStateChanged
        // TODO add your handling code here:
       /* if (domainCheckbox.isSelected()){
            disableDomain();
        }
        else {
            enableDomain();
        }*/
        
        final boolean state = !domainCheckbox.isSelected();
        
        if (state){
            enableDomain();
        }
        else {
            disableDomain();
        }
        
        
        
    }//GEN-LAST:event_domainCheckboxStateChanged

     private void enableDomain() {
         
         final Color enabledColor = Color.white;
         
         domainCostTxt.setEnabled(true);
         domainCostTxt.setBackground(enabledColor);
         
        domainEndDate.setEnabled(true);
        domainEndDate.setBackground(enabledColor);
        
        domainNameTxt.setEnabled(true);
        domainNameTxt.setBackground(enabledColor);
         
    }

    private void disableDomain() {
        final Color disabledColor = Color.getColor("#EBEBE4");
         
         domainCostTxt.setEnabled(false);
         domainCostTxt.setBackground(disabledColor);
         
        domainEndDate.setEnabled(false);
        domainEndDate.setBackground(disabledColor);
        
        domainNameTxt.setEnabled(false);
        domainNameTxt.setBackground(disabledColor);
    }
    
    
    private void packageComboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_packageComboboxItemStateChanged
        // TODO add your handling code here:
        updateTotalCostOnChangingPackage();
    }//GEN-LAST:event_packageComboboxItemStateChanged

     private void updateTotalCostOnChangingDomainCost(){
       
        System.out.println("Started updating totalCost on changing domain cost");
        if (domainCostTxt.isEnabled() && domainCostTxt.getText().length() > 0){
            mDomainPrice = Integer.parseInt(domainCostTxt.getText());
        }
        else {
            mDomainPrice = 0;
        }
        
      
       
        
        totalCostText.setText((mDomainPrice + getSelectedPackageCost() ) + "");
    }
     

    
     private int getSelectedPackageCost(){
         
         final HostingPackage hostingPackage = getSelectedHostingPackage();
         
         if (hostingPackage == null || hostingPackage.equals(HostingPackage.EMPTY_PACKAGE)){
             return 0;
         }
         else {
             return hostingPackage.yearCost;
         }
         
         
     }
     
     private HostingPackage getSelectedHostingPackage(){
         final int index = packageCombobox.getSelectedIndex();
         
         return (HostingPackage) packageCombobox.getItemAt(index);
     }
    
    private void updateTotalCostOnChangingPackage(){
        
            totalCostText.setText((getSelectedPackageCost() + mDomainPrice) + "");
      
    }
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        submitOrder();
    }//GEN-LAST:event_addButtonActionPerformed

    protected void submitOrder(){
        
        final Order order = createOrderBuilder(-1).build();
        
        if (order == null){
            return;
        }
        
        DBUtil.insertOrder(order, new InsertDbListener(){

            @Override
            public void insertedSuccessfully() {
                mAddListener.addedSuccessfully(AddOrderDialog.this);
            }

            @Override
            public void failedToInsert(Throwable throwable) {
                mAddListener.failedToAdd(AddOrderDialog.this, throwable);
            }
        });
    }
     protected Order.Builder createOrderBuilder(final int orderId) {
         
         final Order.Builder builder = new Order.Builder(getSelectedCustomer().id,orderId);
         
         
             builder.setBeginingDate(System.currentTimeMillis());
         
         
         if (domainNameTxt.isEnabled()){
             builder.setDomain(domainNameTxt.getText())
                     .setDomainCost(mDomainPrice)
                     .setDomainEndDate(domainEndDate.getSelectedDate().getTime().getTime())
                     ;
         }
         
         
         
         builder.setHostingPackage(getSelectedHostingPackage().id)
                 
                 .setNote(noteText.getText())
                 ;
         
         try {
         builder.setTotalCost(Integer.parseInt(totalCostText.getText()));    
         }
         
         catch(NumberFormatException ex){
             JOptionPane.showMessageDialog(this, "هنالك خطأ في قيمة الطلب", "خطأ", JOptionPane.ERROR_MESSAGE);
             return null;
         }
                 
         
         return builder;
    }
     
     private Customer getSelectedCustomer(){
         return ((Customer)customerCombobox.getSelectedItem());
     }
       
   
    
    
    private class CustomerComboboxModel implements ComboBoxModel<Customer>{
        
        
        private final ArrayList<Customer> customers;
        private Customer selectedCustomer;
        public CustomerComboboxModel(final ArrayList<Customer> customers){
           this.customers = customers;    
           selectedCustomer = customers.get(customers.size() -1);
        }

        @Override
        public void setSelectedItem(Object anItem) {    
            selectedCustomer = (Customer) anItem;
        }

        @Override
        public Customer getSelectedItem() {
            return selectedCustomer;
        }

        @Override
        public int getSize() {
            return customers.size();
        }

        @Override
        public Customer getElementAt(int index) {
            return customers.get(index);
        }

        @Override
        public void addListDataListener(ListDataListener l) {
        }

        @Override
        public void removeListDataListener(ListDataListener l) {
        }
        
    }
    
    
    private class PackageComboboxModel implements ComboBoxModel<HostingPackage>{
        
        private HostingPackage selectedHostingPackage;
        
        private final ArrayList<HostingPackage> packages;
        
        public PackageComboboxModel(final ArrayList<HostingPackage> hostingPackages){
            packages = hostingPackages;
            packages.add(HostingPackage.EMPTY_PACKAGE);
            selectedHostingPackage = packages.get(packages.size() - 1);
            
           
        }

        @Override
        public void setSelectedItem(Object anItem) {
             selectedHostingPackage = (HostingPackage) anItem;
        }

        @Override
        public HostingPackage getSelectedItem() {
            return selectedHostingPackage;
        }

        @Override
        public int getSize() {
            
            return packages.size();
        }

        @Override
        public HostingPackage getElementAt(int index) {
            return packages.get(index);
        }

        @Override
        public void addListDataListener(ListDataListener l) {
        }

        @Override
        public void removeListDataListener(ListDataListener l) {
        }
        
    }
    
    
    public static interface AddDialogListener {
        void addedSuccessfully(AddOrderDialog dialog);
        void failedToAdd(AddOrderDialog dialog,Throwable throwable);
    }
    
    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    protected javax.swing.JComboBox customerCombobox;
    protected javax.swing.JCheckBox domainCheckbox;
    protected javax.swing.JFormattedTextField domainCostTxt;
    protected datechooser.beans.DateChooserCombo domainEndDate;
    protected javax.swing.JTextField domainNameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    protected javax.swing.JTextField noteText;
    protected javax.swing.JComboBox packageCombobox;
    protected javax.swing.JFormattedTextField totalCostText;
    // End of variables declaration//GEN-END:variables

   

    

   
}
