/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg3a.ui;


import java.awt.Frame;
import java.util.ArrayList;
import pkg3a.utils.DBUtil;
import pkg3a.utils.DBUtil.QueryDbListener;
import pkg3a.utils.Order;

/**
 *
 * @author yazeed44
 */
public class OrdersPanel extends javax.swing.JPanel implements OrdersTable.UpdateOrdersListener  {

    
    private ArrayList<Order> mOrders;
    private final Frame mFrame;
    
    
    
    /**
     * Creates new form OrdersPanel
     */
    public OrdersPanel(final Frame frame) {
        mFrame = frame;
        
        DBUtil.loadOrders(new QueryDbListener<ArrayList<Order>>(){

            @Override
            public void queriedSuccessfully(ArrayList<Order> result) {
                mOrders = result;
                initComponents();
            }

            @Override
            public void failedToQuery(Throwable throwable) {
            }
        });
        
        
        
        
    }
    
   @Override
    public void onUpdateTable(OrdersTable ordersTable) {
        DBUtil.loadOrders(new QueryDbListener<ArrayList<Order>>(){

            @Override
            public void queriedSuccessfully(ArrayList<Order> result) {
                ordersTable.updateTable(result);
            }

            @Override
            public void failedToQuery(Throwable throwable) {
            }
        });
    }
   
    public void onUpdate(){
        onUpdateTable((OrdersTable) ordersTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ordersTable = new OrdersTable(mFrame,mOrders,this);

        setPreferredSize(new java.awt.Dimension(430, 318));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 0));

        ordersTable.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        ordersTable.setPreferredSize(new java.awt.Dimension(490, 318));
        ordersTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ordersTable.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(ordersTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

   

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    javax.swing.JTable ordersTable;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean shouldAllowClick() {
        return true;
    }

    
}
